AdsType.create(:name =>'default')
AdsType.create(:name =>'smth important')
User.create(:email => 'try@example.by', :name => 'admin', :password => '12345678', :role => 'admin')
User.create(:email => 'sss@sss.sss', :name => 'snake', :password => 'ssssssss', :role => 'user')
Ad.create(:description => 'it is description', :name => 'glasses', :state => 1, :user_id => User.where(:role => 'user').first.id, :ads_type_id => AdsType.first.id)
Ad.create(:description => 'it is another', :name => 'tail', :state => 2, :user_id => User.where(:role => 'user').first.id, :ads_type_id => AdsType.first.id)
Ad.create(:description => 'it is dslknsdlcn', :name => 'sdc', :state => 3, :user_id => User.where(:role => 'user').first.id, :ads_type_id => AdsType.first.id)
Ad.create(:description => 'it is sjcnsldnclsd', :name => 'skjcnsdkj', :state => 4, :user_id => User.where(:role => 'user').first.id, :ads_type_id => AdsType.first.id)
Ad.create(:description => 'it is zsdfsdc', :name => '123dvsdvfs', :state => 5, :user_id => User.where(:role => 'user').first.id, :ads_type_id => AdsType.first.id)
Ad.create(:description => 'it is csdfwee', :name => 'yhtgrf', :state => 6, :user_id => User.where(:role => 'user').first.id, :ads_type_id => AdsType.first.id)
